// @ts-nocheck
import { ensureLegacyApp } from './app-context';

(function () {
  'use strict';

  const App = ensureLegacyApp();
  const byId = (id) => document.getElementById(id);
  const qs = (selector) => document.querySelector(selector);
  const qsa = (selector) => document.querySelectorAll(selector);

  const refs = {
    shell: byId('shell'),
    mobileMenuBtn: byId('mobileMenuBtn'),
    sidebarToggle: byId('sidebarToggle'),
    askAiToggle: byId('askAiToggle'),
    topVisitedPages: byId('topVisitedPages'),
    sidebarSearch: qs('.sidebar-search'),
    sidebarSearchInput: qs('.sidebar-search input'),
    navPageButtons: qsa('[data-page]'),
    groupToggles: qsa('[data-toggle="group"]'),
    aiPageSection: qs('[data-page-section="ai-config"]'),
    propertyAnalysisPageSection: qs('[data-page-section="property-analysis"]'),
    spectrumAnalysisPageSection: qs('[data-page-section="spectrum-analysis"]'),
    imageCutoutPageSection: qs('[data-page-section="image-cutout"]'),
    themeSettingsPageSection: qs('[data-page-section="theme-settings"]'),
    projectSkillPageSection: qs('[data-page-section="project-skills"]'),
    projectSkillPanel: byId('projectSkillPanel'),
    aiCallAnalysisPageSection: qs('[data-page-section="ai-call-analysis"]'),
    aiCallAnalysisPanel: byId('aiCallAnalysisPanel'),
    placeholderPageSection: qs('[data-page-section="placeholder"]'),
    businessPageContent: byId('businessPageContent'),
    analysisSearchInput: byId('analysisSearchInput'),
    analysisSheetTabs: byId('analysisSheetTabs'),
    analysisTableWrap: byId('analysisTableWrap'),
    analysisPagination: byId('analysisPagination'),
    analysisPrevPageBtn: byId('analysisPrevPageBtn'),
    analysisNextPageBtn: byId('analysisNextPageBtn'),
    analysisPageInfo: byId('analysisPageInfo'),
    analysisImportExcelBtn: byId('analysisImportExcelBtn'),
    analysisExportJsonBtn: byId('analysisExportJsonBtn'),
    analysisExcelInput: byId('analysisExcelInput'),
    analysisImportStatus: byId('analysisImportStatus'),
    aiConfigForm: byId('aiConfigForm'),
    configStatus: byId('configStatus'),
    configFileInput: byId('configFileInput'),
    aiProviderInputs: qsa('input[name="aiProvider"]'),
    aiProviderOpenRouter: byId('aiProviderOpenRouter'),
    aiProviderLmStudio: byId('aiProviderLmStudio'),
    apiKeyLabelText: byId('apiKeyLabelText'),
    apiKeyNoteText: byId('apiKeyNoteText'),
    aiProviderHelp: byId('aiProviderHelp'),
    apiKeyField: byId('apiKeyField'),
    apiKeyToggle: byId('apiKeyToggle'),
    openrouterApiKey: byId('openrouterApiKey'),
    openrouterBaseUrl: byId('openrouterBaseUrl'),
    appTitle: byId('appTitle'),
    httpReferer: byId('httpReferer'),
    modelDropdown: byId('modelDropdown'),
    modelSelectTrigger: byId('modelSelectTrigger'),
    modelSelectTriggerLabel: byId('modelSelectTriggerLabel'),
    modelSelectPanel: byId('modelSelectPanel'),
    modelSelect: byId('modelSelect'),
    systemPrompt: byId('systemPrompt'),
    temperature: byId('temperature'),
    temperatureValue: byId('temperatureValue'),
    maxTokens: byId('maxTokens'),
    streamEnabled: byId('streamEnabled'),
    jsonMode: byId('jsonMode'),
    logEnabled: byId('logEnabled'),
    ossBucket: byId('ossBucket'),
    ossEndpoint: byId('ossEndpoint'),
    ossObjectKey: byId('ossObjectKey'),
    ossAccessKeyId: byId('ossAccessKeyId'),
    ossAccessKeySecret: byId('ossAccessKeySecret'),
    ossSecretToggle: byId('ossSecretToggle'),
    ossExcelBackupPrefix: byId('ossExcelBackupPrefix'),
    previewModel: byId('previewModel'),
    previewBaseUrl: byId('previewBaseUrl'),
    previewAppTitle: byId('previewAppTitle'),
    previewKey: byId('previewKey'),
    previewFlags: byId('previewFlags'),
    previewPrompt: byId('previewPrompt'),
    previewStatusText: byId('previewStatusText'),
    chatMessages: byId('chatMessages'),
    chatIntroText: byId('chatIntroText'),
    chatInput: byId('chatInput'),
    chatSendBtn: byId('chatSendBtn'),
    assistantDataToggleBtn: byId('assistantDataToggleBtn'),
    clearChatBtn: byId('clearChatBtn'),
    conversationMenuBtn: byId('conversationMenuBtn'),
    conversationMenuLabel: byId('conversationMenuLabel'),
    conversationMenuPanel: byId('conversationMenuPanel'),
    conversationMenuWrap: byId('conversationMenuWrap'),
    conversationMenuSearch: byId('conversationMenuSearch'),
    assistantNewBtn: byId('assistantNewBtn'),
    assistantFullscreenNewBtn: byId('assistantFullscreenNewBtn'),
    assistantExpandBtn: byId('assistantExpandBtn'),
    assistantCloseBtn: byId('assistantCloseBtn'),
    assistantFullscreenTitle: byId('assistantFullscreenTitle'),
    assistantFullscreenSidebar: byId('assistantFullscreenSidebar'),
    assistantFullscreenSearch: byId('assistantFullscreenSearch'),
    loadModelsBtn: byId('loadModelsBtn'),
    importConfigBtn: byId('importConfigBtn'),
    exportConfigBtn: byId('exportConfigBtn'),
    testConfigBtn: byId('testConfigBtn'),
    clearConfigBtn: byId('clearConfigBtn'),
    copyConfigBtn: byId('copyConfigBtn'),
    syncPreviewBtn: byId('syncPreviewBtn'),
    resetPreviewBtn: byId('resetPreviewBtn'),
    refreshPreviewBtn: byId('refreshPreviewBtn'),
    copyEndpointBtn: byId('copyEndpointBtn'),
    aiConfigNav: byId('aiConfigNav'),
  };

  App.refs = refs;
})();
